sudo: false
language: c
compiler: clang
addons:
  apt:
    packages:
      - libpng-dev
      - libjpeg-dev
      - libatlas-base-dev
      - libblas-dev
      - libgsl0-dev
script: cd lib && ./configure && make lib && cd ../bin && make && cd ../site && make source && cd ../test && make && make test
